const express = require('express');
const axios = require('axios');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors({ origin: '*', methods: ['GET','POST','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'] }));
app.options('*', (req, res) => { res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS'); res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization'); res.sendStatus(204); });
app.use(express.json({ limit: '1mb' }));
const H = { 'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36', 'Accept':'application/json, text/plain, */*', 'Accept-Language':'en-US,en;q=0.9', 'Content-Type':'application/json', 'Referer':'https://www.copart.com/lotSearchResults/', 'Origin':'https://www.copart.com', 'copart-country':'US', 'copart-env':'production' };
app.get('/', (req, res) => res.json({ status:'ok', service:'copart-proxy', version:'1.1.0' }));
app.post('/search', async (req, res) => { try { const r = await axios.post('https://www.copart.com/public/lots/search-results', req.body, { headers: H, timeout: 15000 }); res.json(r.data); } catch(e) { res.status(e.response?.status||500).json({ error: e.message }); } });
app.get('/lot/:n', async (req, res) => { try { const r = await axios.get(`https://www.copart.com/public/data/lot/details/${req.params.n}`, { headers: H, timeout: 10000 }); res.json(r.data); } catch(e) { res.status(e.response?.status||500).json({ error: e.message }); } });
app.listen(PORT, () => console.log(`Copart proxy v1.1.0 on port ${PORT}`));
